### ISSUE TITLE
Make the site responsive

### ISSUE THREAD

**Issue by TypicalFence** [barrucadu/lainonlife#19]
I think it would be nice if the site would be responsive.

This is not that important, I guess, most people won't use it on a smartphone.
Nevertheless I think it would be a "nice to have"-feature.

I tend to use the site on the go, on mine, so I would be happy about it. ^^

**Comment by barrucadu** [comment]
This would be nice, but I fear we're rapidly escaping my front-end skills.

**Comment by AlexFence** [comment]
I am not thinking of something, over the top. We could even keep what's already there for the desktop.

Would it help if it was heavily commented? or something similar?

**Comment by barrucadu** [comment]
Oh, I'm not saying I'm *against* a responsive site.  I just won't be able to help much.

**Comment by fuerbringer** [comment]
I could totally help out with this if no one else is gonna do it. At work I've implemented a couple responsive layouts for 10+ year old sites so this shouldn't be too hard. I have time this weekend, so I can do it unless @AlexFence beats me to it.

**Comment by AlexFence** [comment]
I actually wanted to start now @fuerbringer ^^ but I am a bit rusty with css, I just got too used using css frameworks, thats why I want to do it actually. But feel free to suggest improvements if I beat you.

**Comment by fuerbringer** [comment]
Alright! Go ahead. Then I'll try to help once you submit the PR.

**Comment by comradesmith** [comment]
Hey I've put together a shot at making the playlist reponsive but I'm not having much luck running the site locally. It's here: https://github.com/barrucadu/lainonlife/compare/master...comradesmith:issue_19_responsiveness

I'm hoping to find some time to spin up a NixOS environment so I can get a local instance more easily, but I can't really guarantee when I'll be able to do that. Feedback on my changes would be much appreciated, thanks!

**Comment by AlexFence** [comment]
not being able to run it anymore is also something that was hindering me tbqh @comradesmith.
I also used to attach it to the lainon.life backed, instead of running my own, which used to be easier, not too sure how I did it.

maybe checkout my [cewl fork](https://github.com/AlexFence/lainonlife), I apprently even wrote a lot of css for it, but its been so long...

I think I just hardcoed the url into all ajax calls :thinking: and served the index.html with python (python3 -m http.server) or something like that 
https://github.com/AlexFence/lainonlife/blob/b7032d4c5f30dbdd9da2acadc41efde2f504f176/frontend/js/radio.js#L20

**Comment by AlexFence** [comment]
okay I just checked the current state of things~ seems like a lot changed. 

@comradesmith just set the "icecast_status_urll" in the config.json to "https://lainon.life/radio/status-json.xsl" and stuff should work™, it at least used to. You should now be able to "run" the frontend with the data of the deployed instance~

**Comment by comradesmith** [comment]
Thanks @AlexFence, that makes things a bit easier, but its still acting a bit weird for me. I've had a quick look at your fork and you've done a lot!

I'm gonna try writing a Docker-compose config for the site and its requirements cause thats probably more up my alley than learning NixOS

I'll let you know how it goes

**Comment by AlexFence** [comment]
@comradesmith yeah I've done some css, feel free to just merge what ever from there into your solution!

yeah a docker setup would be really nice~

**Comment by TypicalFence** [comment]
@barrucadu this can be closed as of #40
