### ISSUE TITLE
Set up a staging site

### ISSUE THREAD

**Issue by barrucadu** [barrucadu/lainonlife#34]
As evidenced by this morning, just checking configuration is syntactically valid and looks reasonable before deploying is a good way to cause downtime.

Fortunately, NixOS containers should make it trivial to run a staging site.

**Comment by AlexFence** [comment]
I assume NixOS-containers only run on NixOS.

Wouldn't it be better to use a suited platform independent alternative to them? 
Like docker or vagrant or something like that.

**Comment by barrucadu** [comment]
The advantage of a NixOS container is that the server is already running NixOS, so I can start up a totally identical container like so:

```
$ sudo nixos-container create staging --config-file /etc/nixos/configuration.nix
$ sudo nixos-container start staging
```

The only thing to do probably is to hardlink some music files into the container and change its nginx and icecast ports and expose those ports on the public IP.
