### ISSUE TITLE
Suggestion: playlist upload feature

### ISSUE THREAD

**Issue by pussinboot** [barrucadu/lainonlife#37]
it would lower the barrier of entry for people considering djing, this can be done with a vetting procedure or as an auto-dj type thing

**Comment by barrucadu** [comment]
What would this be like?  I'm having trouble imagining it.

**Comment by pussinboot** [comment]
multiple file upload with a way to rearrange tracks
one person uploads a playlist, someone else listens to make sure it isn't just noise
once approved, auto-dj lets you schedule a playlist to play instead of regular programming
