### ISSUE TITLE
File list links return 404 Not Found

### ISSUE THREAD

**Issue by 3x3sauce** [barrucadu/lainonlife#42]
The playlist links on the site player (https://lainon.life/file-list/everything.html, https://lainon.life/file-list/cyberia.html, etc) are currently returning 404 errors instead of file lists.

**Comment by barrucadu** [comment]
Solved, thanks

**Comment by SegoCode** [comment]
Hi 👋
Now its returning 404 on https://lainon.life/file-list/everything.html, https://lainon.life/file-list/cyberia.html, https://lainon.life/file-list/cafe.html and https://lainon.life/file-list/swing.html
