### ISSUE TITLE
Vote to skip?

### ISSUE THREAD

**Issue by barrucadu** [barrucadu/lainonlife#7]
The current playlist is planned hours in advance.  I do think that occasionally playing a complete album is nicer than purely global shuffle, but it does mean we can't really have a request form like r/a/dio.  The next best thing is a link to vote to skip an upcoming track.

**Steps:**

1. Add an AJAX-powered button to send a "skip track" request to the backend.
2. Keep track of number of listeners of the channel.
    - Maybe it should only be listeners who are listening via lainon.life, rather than lainchan.org or other sites.  Those other people won't be voting.
    - The number of listeners on lainon.life can be measured by logging unique IPs over a short time.
3. Keep track of number of skip votes.
4. Remove the track from the playlist when the skip votes reach a certain proportion of the listeners.

**Comment by fuerbringer** [comment]
Sounds OK as long as it's to skip the _upcoming_ track, not the currently playing one (would be kind of annoying).

Also this opens the possibility to bots spamming the skip track button. Maybe implement it so that for each playing track you can only vote once to skip.

**Comment by barrucadu** [comment]
I was thinking for every upcoming track have a skip button.
