### ISSUE TITLE
Absolute include paths

### ISSUE THREAD

**Issue by fuerbringer** [barrucadu/lainonlife#9]
Is there a reason why the backend scripts `file-list.sh` and `backend.py` are reading files from an absolute path (`/srv/http`)?

I'm not much of a Python programmer, but I could imagine this causing issues when deploying the application on different kinds of operating systems. Debian for example uses `/var/www/html` as webserver root.

So basically I'm suggesting using relative paths. That way the web application _should_ be able to run from any directory.

**Comment by barrucadu** [comment]
There's no reason.

Other than the location of `bash` and `python`, there's quite a bit of environmental assumption in the scripts.  Really, I should add the following optional arguments (defaulting to their current values, unless noted):

- `backend.py`:
    - http directory, defaulting to the current directory
    - music directory
    - MPD host
- `file-list.sh`: (probably rewrite as a small python script for ease of argument parsing)
    - output directory, defaulting to the current directory
    - music directory
- `metrics.py`:
    - Icecast host and port
    - InfluxDB host, port, user, password, and database
- `schedule.py`:
    - MPD host

I think that covers all the bases.
